In [123]:
import numpy as np
import time
'''
puzzle = [
    [8,7,4, 1,9,2, 0,0,3],
    [2,3,0, 0,7,0, 8,1,9],
    [6,1,9, 3,0,8, 4,7,2],

    [0,0,2, 7,0,5, 0,8,0],
    [7,0,0, 0,1,0, 0,2,5],
    [0,5,0, 0,2,0, 7,0,0],

    [9,6,7, 5,0,1, 2,4,8],
    [0,8,0, 2,4,7, 0,9,0],
    [4,2,1, 9,8,0, 5,0,7]
 ]'''

puzzle = [
    [3,8,9, 2,7,0, 6,0,4],
    [7,0,6, 9,1,0, 2,8,5],
    [0,0,0, 8,4,0, 0,3,0],

    [6,0,4, 3,0,2, 0,0,0],
    [0,1,8, 0,0,7, 0,0,2],
    [0,0,0, 6,0,0, 0,5,0],

    [0,0,0, 7,0,0, 1,0,6],
    [1,0,0, 0,0,8, 0,0,0],
    [0,6,3, 0,0,0, 5,7,0]
    ]

start = time.time()

solve = np.zeros((9, 9, 10), dtype = "int32")

#priprema
for i in range(9):
    for j in range(9):
        for k in range(9):
            solve[i,j,k] = k+1

for i in range(9):
    for j in range(9):
        if(puzzle[i][j] != 0):
            #print(i)
            #print(j)
            #print(puzzle[i][j])
            #print("---")
            cut = puzzle[i][j]-1
            solve[i][j][cut] = 0
            solve[i][j][9] = cut + 1
            for k in range(9):
                solve[i][j][k] = 0
                solve[k][j][cut] = 0
                solve[i][k][cut] = 0
            x = (int)(i/3)
            y = (int)(j/3)

            for m in range(3):
                for n in range(3):
                    solve[x*3+m][y*3+n][cut] = 0
#print(solve[0][0])
#solvig
def try_solve(solve):
    fleg = True
    while fleg:
        fleg = False 
        for i in range (9):
            for j in range (9):

                if(solve[i][j][9] == 0):
                    for k in range(9):
                        po_k = False
                        vr_k = -1
                        po_x = False
                        vr_x = -1
                        po_y = False
                        vr_y = -1
                        po_s = False
                        vr_s = -1


                        x_k = (int)(i/3)
                        y_k = (int)(j/3)
                        for m in range(3):
                            for n in range(3):
                                if(solve[x_k*3+m][y_k*3+n][k] != 0):
                                    if(vr_k == -1):
                                        vr_k = solve[x_k*3+m][y_k*3+n][k]
                                        po_k = True
                                    else:
                                        po_k = False

                        for n in range(9):
                            if(solve[i][j][n] != 0):
                                if(vr_s == -1):
                                    vr_s = solve[i][j][k]
                                    po_s = True
                                else:
                                    po_s = False
                            if(solve[i][n][k] != 0):
                                if(vr_x == -1):
                                    vr_x = solve[i][j][k]
                                    po_x = True
                                else:
                                    po_x = False
                            if(solve[n][j][k] != 0):
                                if(vr_y == -1):
                                    vr_y = solve[i][j][k]
                                    po_y = True
                                else:
                                    po_y = False
                        if((po_x or po_y or po_s or po_k) and solve[i][j][k] != 0) :
                            fleg = True
                            #print(i)
                            #print(j)
                            #print(k)
                            #print(solve[i][j][k])
                            #print("***")
                            cut = solve[i][j][k]
                            solve[i][j][k] = 0
                            solve[i][j][9] = cut
                            for z in range(9):
                                solve[i][j][z] = 0
                                solve[z][j][k] = 0
                                solve[i][z][k] = 0
                            x = (int)(i/3)
                            y = (int)(j/3)

                            for m in range(3):
                                for n in range(3):
                                    solve[x*3+m][y*3+n][k] = 0
    return solve
  
solve = try_solve(solve)
print(time.time() - start)

print("----")
mat = np.zeros((9,9), dtype = "int32")
for i in range(9):
    for j in range(9):
        mat[i][j] = solve[i][j][9]      
            
print(mat)
#solve


0.020943880081176758
----
[[3 8 9 2 7 5 6 1 4]
 [7 4 6 9 1 3 2 8 5]
 [2 5 1 8 4 6 7 3 9]
 [6 7 4 3 5 2 8 9 1]
 [5 1 8 4 9 7 3 6 2]
 [9 3 2 6 8 1 4 5 7]
 [8 9 5 7 3 4 1 2 6]
 [1 2 7 5 6 8 9 4 3]
 [4 6 3 1 2 9 5 7 8]]
